# Generated by Django 3.1.1 on 2020-09-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('designer', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('users_who_basketed', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
