# Generated by Django 3.1.1 on 2020-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationery',
            name='price',
            field=models.FloatField(),
        ),
    ]
