# Generated by Django 3.1.1 on 2020-09-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
        ('stationery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationery',
            name='users_who_basketed',
        ),
        migrations.AddField(
            model_name='stationery',
            name='users_who_basketed',
            field=models.ManyToManyField(to='jwt_auth.User'),
        ),
    ]
