# Generated by Django 3.1.1 on 2020-09-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_remove_user_basket'),
        ('stationery', '0002_auto_20200912_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationery',
            name='users_who_basketed',
            field=models.ManyToManyField(related_name='basket', to='jwt_auth.User'),
        ),
    ]
