# Generated by Django 3.1.1 on 2020-09-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
        ('stationery', '0003_auto_20200911_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationery',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer', to='designers.designer'),
        ),
    ]
